### ISSUE TITLE
Uncaught TypeError: Cannot read property 'return' of undefined

### ISSUE THREAD

**Issue by hahmjt** [Gert-dev/php-integrator-tooltips#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [php-integrator-tooltips](https://github.com/Gert-dev/php-integrator-tooltips) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'return' of undefined

```
At /Users/hahmjt/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:17

TypeError: Cannot read property 'return' of undefined
    at Object.module.exports.buildTooltipForFunction (/Users/hahmjt/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:17:9)
    at MethodProvider.module.exports.MethodProvider.getTooltipForWord (/Users/hahmjt/.atom/packages/php-integrator-tooltips/lib/MethodProvider.coffee:27:24)
    at MethodProvider.module.exports.AbstractProvider.showPopoverFor (/Users/hahmjt/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:119:24)
    at HTMLSpanElement.<anonymous> (/Users/hahmjt/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:88:22)
    at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:39 core:move-down (atom-text-editor.editor.is-focused)
     -0:36.7.0 core:cut (atom-text-editor.editor.is-focused)
     -0:36.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:36.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:36.1.0 editor:indent (atom-text-editor.editor.is-focused)
  3x -0:35.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:35 core:move-up (atom-text-editor.editor.is-focused)
     -0:34.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:34.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:34.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:34.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:31.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:30.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -0:14.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  5x -0:12.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
php-integrator-autocomplete-plus, v0.2.1
php-integrator-base, v0.2.0
php-integrator-tooltips, v0.2.0

# Dev
No dev packages
```

**Comment by Gert-dev** [comment]
I think this is fixed with the more recent 0.3 version of the base package. Feel free to reopen if it happens again.
